program TEMPLATE; {INICIA PROGRAMA}
{ACÁ PUEDEN IR LAS VARIABLES GLOBALES}
{ACÁ PUEDEN IR LOS PROCEDURES}
{ACÁ PUEDEN IR LAS FUNCIONES}
var {VARIABLES LOCALES}
begin {COMIENZA PROGRAMA PRINCIPAL}
end. {TERMINA PROGRAMA PRINCIPAL}