ORG 1000H
MSJ1 DB "INGRESE UN NUMERO: "
MSJ2 DB "ERROR"
NUM0 DB "CERO"
NUM1 DB "UNO"
NUM2 DB "DOS"
NUM3 DB "TRES"
NUM4 DB "CUATRO"
NUM5 DB "CINCO"
NUM6 DB "SEIS"
NUM7 DB "SIETE"
NUM8 DB "OCHO"
NUM9 DB "NUEVE"
FIN DB ?

ORG 1500H
NUM DB ?; Dirección de memoria reservada para guardar numeros

ORG 4000H; Esta subrutina comprueba que el carácter sea un dígito
COMPROBAR: CMP BYTE PTR [BX], 30H
JC NO_ES
CMP BYTE PTR [BX], 39H
JZ SI_ES
JNC NO_ES
SI_ES: MOV CL, 0FFH
JMP TERMINAR
NO_ES: MOV CL, 00H
TERMINAR: RET

ORG 3500H; Esta subrutina imprime el número en letras
IMPRIMIR: CMP BYTE PTR [BX], 30H
JNZ PASAR1
MOV DH, 1; Settear DL en 1
MOV BX, OFFSET NUM0
MOV AL, OFFSET NUM1 - OFFSET NUM0
JMP PASAR_IMP; A imprimir
PASAR1: CMP BYTE PTR [BX], 31H
JNZ PASAR2
MOV BX, OFFSET NUM1
MOV AL, OFFSET NUM2 - OFFSET NUM1
JMP PASAR_IMP; A imprimir
PASAR2: CMP BYTE PTR [BX], 32H
JNZ PASAR3
MOV BX, OFFSET NUM2
MOV AL, OFFSET NUM3 - OFFSET NUM2
JMP PASAR_IMP; A imprimir
PASAR3: CMP BYTE PTR [BX], 33H
JNZ PASAR4
MOV BX, OFFSET NUM3
MOV AL, OFFSET NUM4 - OFFSET NUM3
JMP PASAR_IMP; A imprimir
PASAR4: CMP BYTE PTR [BX], 34H
JNZ PASAR5
MOV BX, OFFSET NUM4
MOV AL, OFFSET NUM5 - OFFSET NUM4
JMP PASAR_IMP; A imprimir
PASAR5: CMP BYTE PTR [BX], 35H
JNZ PASAR6
MOV BX, OFFSET NUM5
MOV AL, OFFSET NUM6 - OFFSET NUM5
JMP PASAR_IMP; A imprimir
PASAR6: CMP BYTE PTR [BX], 36H
JNZ PASAR7
MOV BX, OFFSET NUM6
MOV AL, OFFSET NUM7 - OFFSET NUM6
JMP PASAR_IMP; A imprimir
PASAR7: CMP BYTE PTR [BX], 37H
JNZ PASAR8
MOV BX, OFFSET NUM7
MOV AL, OFFSET NUM8 - OFFSET NUM7
JMP PASAR_IMP; A imprimir
PASAR8: CMP BYTE PTR [BX], 38H
JNZ PASAR9
MOV BX, OFFSET NUM8
MOV AL, OFFSET NUM9 - OFFSET NUM8
JMP PASAR_IMP; A imprimir
PASAR9: MOV BX, OFFSET NUM9
MOV AL, OFFSET FIN - OFFSET NUM9
PASAR_IMP: INT 7
RET

ORG 3000H
INGRESAR: MOV BX, OFFSET MSJ1; Primer mensaje
MOV AL, OFFSET MSJ2 - OFFSET MSJ1; Pasar su longitud
INT 7; Imprimirlo
MOV BX, OFFSET NUM; Pasar la dirección para guardar el número
INT 6; Pedirle al usuario que ingrese un número
CALL COMPROBAR; Pasar código a BX como referencia
CMP CL, 0
JZ NO_VALIDO; Si CL es igual a 0, es porque el carácter ingresado no era un número
CALL IMPRIMIR
JMP FINAL
NO_VALIDO: MOV BX, OFFSET MSJ2
MOV AL, OFFSET NUM0 - OFFSET MSJ2
INT 7
MOV CL, NUM; Pasar el número a CL
FINAL: RET

ORG 2000H
MOV BX, 0
MOV CX, 0
MOV DH, 0; Settearlo en 0
MOV DL, 2; Terminar el programa al ejecutar dos veces el número 0
BUCLE: CMP DL, 0
JZ CHAU; Si se leyó 2 veces cero, terminar el programa
CALL INGRESAR
CMP DH, 1
JNZ BUCLE
DEC DL; Decrementar si se leyó un 0 la última vez
MOV DH, 0; Settearlo de vuelta en 0
JMP BUCLE
CHAU: INT 0
END
