;Constantes
PIO EQU 30H

ORG 1000H
MSJ DB "LLAVE PRENDIDA"
MSJ2 DB "LLAVE APAGADA"
FIN DB ?

ORG 2000H
MOV AL, 0FFH
OUT PIO+2, AL
IN AL, PIO
AND AL, 10000000B
CMP AL, 10000000B
JNZ NO_ES
  MOV BX, OFFSET MSJ
  MOV AL, OFFSET MSJ2 - OFFSET MSJ
  INT 7
  JMP TERMINAR
NO_ES: MOV BX, OFFSET MSJ2
  MOV AL, OFFSET FIN - OFFSET MSJ2
  INT 7
TERMINAR: INT 0
END
